from src import db

class ExcessStockModel(db.Model):
    __tablename__ = "excess_stock"
    ID = db.Column(db.Integer,primary_key=True)
    EX_STK_DATE = db.Column(db.Date, nullable=True)
    STORE_CODE = db.Column(db.String(100), nullable=True)
    STORE_NAME = db.Column(db.String(255), nullable=True)
    CITY = db.Column(db.String(255), nullable=True)
    REGION = db.Column(db.String(255), nullable=True)
    STATE = db.Column(db.String(255), nullable=True)
    BRANCH_TYPE = db.Column(db.String(255), nullable=True)
    STORE_CATEGORY = db.Column(db.String(255), nullable=True)
    FRANCH_TYPE = db.Column(db.String(255), nullable=True)
    ITEM_CODE = db.Column(db.String(255), nullable=True)
    ITEM_NAME = db.Column(db.String(255), nullable=True)
    BRAND = db.Column(db.String(255), nullable=True)
    ITEM_GROUP = db.Column(db.String(255), nullable=True)
    ACTUAL_ITEM = db.Column(db.String(255), nullable=True)
    MODELNO = db.Column(db.String(255), nullable=True)
    SECTION = db.Column(db.String(255), nullable=True)
    ITEM_FLAG = db.Column(db.String(255), nullable=True)
    ITEM_STATUS = db.Column(db.String(255), nullable=True)
    STOCK_QTY = db.Column(db.Integer, default=0)
    TOTAL_STOCK = db.Column(db.Numeric(38, 6), default=0.000000)
    REV_STOCK_QTY = db.Column(db.Integer, default=0)
    REV_TOTAL_STOCK = db.Column(db.Numeric(38, 6), default=0.000000)
    OVERALL_AGE = db.Column(db.Integer, default=0)
    DEAD = db.Column(db.Integer, default=0)
    ALLOCATED = db.Column(db.Integer, default=0)
    NOT_ALLOCATED = db.Column(db.Integer, default=0)
    SALES_QTY_30DAYS = db.Column(db.Integer, default=0)
    COST_PRICE_30DAYS = db.Column(db.Numeric(38, 6), default=0.000000)
    ST_IT_FLAG = db.Column(db.String(255), nullable=True)
    IT_FLAG = db.Column(db.String(255), nullable=True)
    DEMO_FLAG = db.Column(db.String(1), default='N')
    EOL_FLAG = db.Column(db.String(1), default='Y')
    DATA_SOURCE = db.Column(db.String(255), nullable=True)
    NO_OF_PIECES = db.Column(db.String(255), nullable=True)
    DSI = db.Column(db.String(255), nullable=True)
    IT_NO_OF_PIECES = db.Column(db.String(255), nullable=True)
    IT_DSI = db.Column(db.String(255), nullable=True)
    SALES_NO_OF_PIECES = db.Column(db.String(255), nullable=True)
    SALES_IT_NO_OF_PIECES = db.Column(db.String(255), nullable=True)
    ALGO_TYPE = db.Column(db.String(255), nullable=True)
    DATA_REFRESH_TIME = db.Column(db.DateTime, nullable=True)


    						
