from src import db

class MStockOptimizationModel(db.Model):
    __tablename__ = "m_stock_optimization"
    ID_NO = db.Column(db.Integer,primary_key=True,autoincrement=True)
    OPT_DATE = db.Column(db.Date, nullable=True)
    ITEM_ID = db.Column(db.Integer, nullable=True)
    MODELNO = db.Column(db.String(255, collation='latin1_swedish_ci'), nullable=True)
    BRAND = db.Column(db.String(255), nullable=True)
    FROM_STORE_CODE = db.Column(db.String(10, collation='latin1_swedish_ci'), nullable=True)
    FROM_STORE_NAME = db.Column(db.String(60, collation='latin1_swedish_ci'), nullable=True)
    FROM_CITY = db.Column(db.String(255, collation='latin1_swedish_ci'), nullable=True)
    FROM_STATE = db.Column(db.String(255, collation='latin1_swedish_ci'), nullable=True)
    FROM_REGION = db.Column(db.String(255, collation='latin1_swedish_ci'), nullable=True)
    TO_STORE_CODE = db.Column(db.String(10, collation='latin1_swedish_ci'), nullable=True)
    TO_STORE_NAME = db.Column(db.String(60, collation='latin1_swedish_ci'), nullable=True)
    TO_CITY = db.Column(db.String(255, collation='latin1_swedish_ci'), nullable=True)
    TO_STATE = db.Column(db.String(255, collation='latin1_swedish_ci'), nullable=True)
    TO_REGION = db.Column(db.String(255, collation='latin1_swedish_ci'), nullable=True)
    DEMAND_DAYS = db.Column(db.String(255), nullable=True)
    DEMAND_QTY_ORIG = db.Column(db.Integer, default=0)
    DEMAND_QTY = db.Column(db.Integer, default=0)
    SUPPLY_QTY = db.Column(db.Integer, default=0)
    REQUESTED_QTY = db.Column(db.Integer, default=0)
    SUPPLIED_QTY = db.Column(db.Integer, default=0)
    DEMAND_STORE_UNMET_QTY = db.Column(db.Integer, default=0)
    SUPPLY_STORE_UNSUPPLIED_QTY = db.Column(db.Integer, default=0)
    DEMAND_STORE_SALES_QTY = db.Column(db.Integer, default=0)
    DEMAND_STORE_STOCK_QTY = db.Column(db.Integer, default=0)
    COST_PRICE = db.Column(db.Numeric(53, 0), nullable=True)
    TRANSFER_ITERATION = db.Column(db.String(255, collation='latin1_swedish_ci'), nullable=True)
    DATA_SOURCE = db.Column(db.String(255, collation='latin1_swedish_ci'), nullable=True)
    REMARKS = db.Column(db.String(255, collation='latin1_swedish_ci'), nullable=True)
    TRANS_FLAG = db.Column(db.String(1, collation='latin1_swedish_ci'), nullable=True)
    EOL_FLAG = db.Column(db.String(1), nullable=True)
    SECTION = db.Column(db.String(255, collation='latin1_swedish_ci'), nullable=True)
    STATE = db.Column(db.String(255), nullable=True)
    DATA_REFRESH_TIME = db.Column(db.DateTime, nullable=True)
    id = db.Column(db.Integer)
    approved_qty = db.Column(db.Integer, nullable=True)
    t_approved_by = db.Column(db.String(45), nullable=True)
    t_approved_date = db.Column(db.Date, nullable=True)
    po_number = db.Column(db.String(250), nullable=True)
    po_date = db.Column(db.Date, nullable=True)
    t_approved_flag = db.Column(db.String(5), nullable=True)
    p_approved_flag = db.Column(db.String(5), nullable=True)
    t_couriered_flag = db.Column(db.String(5), nullable=True)
    d_couriered_date = db.Column(db.Date, nullable=True)
    p_approved_by = db.Column(db.String(45), nullable=True)
    p_approved_date = db.Column(db.Date, nullable=True)
    t_couriered_qty = db.Column(db.Integer, nullable=True)
    t_received_qty = db.Column(db.Integer, nullable=True)
    d_received_date = db.Column(db.Date, nullable=True)
    t_received_flag = db.Column(db.String(5), nullable=True)
    p_yet_to_procure_projected_qty = db.Column(db.Integer, nullable=True)
    p_projection_days = db.Column(db.Integer, nullable=True)
    p_actual_po_qty = db.Column(db.Integer, nullable=True)
    p_final_po_qty = db.Column(db.Integer, nullable=True)
    p_final_po_flag = db.Column(db.String(30), nullable=True)

